const Languages = {
    common: {
        cancel: 'Hủy',
        OK: 'Chọn',
        back: 'Quay lại',
        yes: 'Có',
        no: 'Không',
        close: 'Đóng',
        search: 'Tìm kiếm',
        agree: 'Đồng ý',
        or: 'Hoặc',
        continue: 'Tiếp tục',
        currency: 'VND',
        percent: '%',
        addBank: 'Thêm tài khoản',
        notAccount: 'Bạn chưa có tài khoản',
        hasAccount: 'Bạn đã có tài khoản',
        news: 'Tin tức',
        historyTransaction: 'Lịch sử giao dịch',
        confirmOtp: 'Xác nhận OTP'
    },
    errorMsg: {
        noInternet: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        sessionExpired: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        userNameRequired: 'Họ và tên không được để trống',
        userNameLength: 'Họ và tên không được ít hơn 8 ký tự',
        userNameRegex: 'Không được chứa ký tự đặc biệt hoặc số',
        errIllegal: 'Mật khẩu không hợp lệ',
        emailNull: 'Email không được để trống',
        emailRegex: 'Email không đúng định dạng',
        cardNull: 'Số CMND/CCCD không được để trống',
        cardRegex: 'Số CMND/CCCD phải là số',
        cardCheck: 'Số CMND/CCCD không hợp lệ',
        pwdNull: 'Mật khẩu không được để trống',
        pwdCheck: 'Mật khẩu không được ít hơn 8 ký tự',
        conFirmPwd: 'Xác nhận mật khẩu không trùng khớp với mật khẩu',
        emptyAmount: 'Bạn chưa nhập số tiền',
        minAmount: 'Số tiền nạp/rút tối thiểu là 100.000 vnđ',
        phoneIsEmpty: 'Số điện thoại không được để trống',
        phoneRegex: 'Số điện thoại không đúng định dạng',
        phoneCount: 'Số điện thoại chỉ được 10 số',
        jobEmpty: 'Nghề nghiệp không được để trống',
        taxIdEmpty: 'Mã số thuế không được để trống',
        taxIdSyntax: 'Mã số thuế không được ít hơn 10 ký tự',
        specialCharacters: 'Không được chứa kí tự đặc biệt',
        birthdayEmpty: 'Ngày sinh ',
        birthdayNotNumber: 'Ngày sinh không đúng định dạng ví dụ: 1970-01-01',
        birthdayAge18: 'Chưa đủ 18 tuổi',
        birthdayAge95: 'Vượt quá 95 tuổi',
        errProvince: 'Thành phố không được bỏ trống',
        errDistrict: 'Quận huyện không được bỏ trống',
        errWard: 'Xã phường không được bỏ trống',
        errFunds: 'Nguồn tiền không được bỏ trống',
        errMoveto: 'Chuyển tới không được bỏ trống',
        errKeyBook: 'Mã sổ không được bỏ trống',
        errMsgOldPwdCompare: 'Mật khẩu cũ bạn nhập không đúng',
        errMsgCurrentPwdCompare: 'Mật khẩu nhập lại không trùng khớp',
        errMsgEmpty: 'Mật khẩu nhập không được để trống',
        errMsgLength: 'Mật khẩu nhập phải từ 8 kí tự trở lên',
        errMsgSpecialChar: 'Mật khẩu nhập không được chứa kí tự đặc biệt',
        errMsgSpaceChar: 'Mật khẩu nhập không được chứa kí tự trống',
        errMsgUpperChar: 'Mật khẩu phải có 1 kí tự in hoa',
        errMsgGender: 'Giới tính không được bỏ trống',
        uploading: 'Đang tải ảnh lên',
        uploadingError: 'Tải ảnh thất bại',
        errStk: 'Số tài khoản hoặc số thẻ vượt quá giới hạn cho phép',
        errStkEmpty: 'Số tài khoản hoặc số thẻ trống',
        errNameEmpty: 'Tên tài khoản ngân hàng trống',
        errBankEmpty: 'Ngân hàng chưa được chọn',
        errMethodMoney: 'Vui lòng cập nhật phương thức nhận tiền',
        errMethodWithdrawMoney: 'Vui lòng cập nhật phương thức rút tiền',
        errChooseMethodMoney: 'Vui lòng chọn phương thức nhận tiền',
        errNoEnoughMoney: 'Hạn mức giao dịch tối thiểu <br />100.000 VND',
        errLimit: 'Số dư hiện tại không đủ để giao dịch',
        updatePwd: 'Xác nhận thay đổi mật khẩu thành công',
        errEmptyBirthday: '01/01/1920',
        errKYC: 'Vui lòng xác thực CMT/CCCD để thực hiện việc rút tiền',
        notKYc: ' chưa xác thực CMT/CCCD'
    },
    menu: {
        invest: 'Đầu tư',
        asset: 'Tài sản',
        transaction: 'Giao dịch',
        support: 'Hỗ trợ',
        sologan: 'x2 lợi nhuận từ dòng tiền'
    },
    home: {
        univest: 'Túi Univest',
        totalassets:'Tổng tài sản',
        Growth:'Tăng trưởng ',
        profitable:'Sinh lời 4% / năm',
        profiMonth:'Lợi nhuận tháng này',
        money:'10000000',
        unit:'VND',
        recharge:'Nạp tiền',
        bag1:'túi',
        invests:'UNIVEST',
        withdrawMoney:'Rút tiền về',
        moneys :'Ngân Lương',
        Management : 'Quản lý',
        asset:'tài sản',
        history:'Lịch sử',
        transaction:'giao dịch',
        support:'Hỗ trợ',
        customer:'Khách hàng'
    },
    popup:{
        title: 'Thông báo popup',
        description: 'Đây là nội dung thông báo'
    },
    otp: {
     title: 'Xác nhận OTP',
     warnning: 'Mã xác thực đã được gửi đến số điện thoại %phone. Mã hết hiệu lực sau %time giây.'
    },
    footer: {
        title: 'TẢI XUỐNG UNIVEST ĐỂ TRẢI NGHIỆM NHỮNG DỊCH VỤ TỐT NHẤT'
    }
};

export default Languages;
